# Generated by Django 5.2.12 on 2026-03-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Canteen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=500)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                (
                    "lead_time_config",
                    models.IntegerField(
                        default=6,
                        help_text="Minimum hours before a cake reservation can be placed.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNDER_REVIEW", "Under Review"),
                            ("REJECTED", "Rejected"),
                            ("ACTIVE", "Active (auto-managed)"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("BUSY", "Busy"),
                            ("EMERGENCY_CLOSURE", "Emergency Closure"),
                        ],
                        default="UNDER_REVIEW",
                        help_text="Current operational status — from Canteen Operational state diagram.",
                        max_length=20,
                    ),
                ),
                (
                    "documents",
                    models.FileField(blank=True, null=True, upload_to="canteen_docs/"),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason provided by Admin if registration is rejected.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CanteenHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.TextField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Discount percentage (0–100).",
                        max_digits=5,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="dish_photos/"),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("category", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DishReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(help_text="Rating from 1 to 5.")),
                ("review_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
