# Generated by Django 5.2.12 on 2026-03-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("canteens", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="canteen",
            name="manager",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="canteen",
                to="users.canteenmanagerprofile",
            ),
        ),
        migrations.AddField(
            model_name="canteenholiday",
            name="canteen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidays",
                to="canteens.canteen",
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="canteen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="canteens.canteen",
            ),
        ),
        migrations.AddField(
            model_name="dishreview",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="users.customerprofile",
            ),
        ),
        migrations.AddField(
            model_name="dishreview",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="canteens.dish",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="canteenholiday",
            unique_together={("canteen", "date")},
        ),
    ]
