# Generated by Django 5.2.12 on 2026-03-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteens", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canteen",
            name="documents",
        ),
        migrations.AddField(
            model_name="canteen",
            name="aadhar_card",
            field=models.FileField(
                blank=True,
                help_text="Aadhar card of the canteen manager.",
                null=True,
                upload_to="documents/",
            ),
        ),
        migrations.AddField(
            model_name="canteen",
            name="hall_approval_form",
            field=models.FileField(
                blank=True,
                help_text="Hall Approval Form for the canteen.",
                null=True,
                upload_to="documents/",
            ),
        ),
        migrations.AddField(
            model_name="canteen",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Cover photo of the canteen.",
                null=True,
                upload_to="canteen_images/",
            ),
        ),
    ]
