# Generated by Django 5.2.12 on 2026-03-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_veg',
            field=models.BooleanField(default=True, help_text='True for vegetarian, False for non-vegetarian.'),
        ),
    ]
