# Generated by Django 5.2.12 on 2026-03-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canteens", "0003_dish_is_veg"),
        ("canteens", "0003_remove_canteen_documents_canteen_aadhar_card_and_more"),
    ]

    operations = []
