# Generated by Django 5.2.12 on 2026-03-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteens", "0004_merge_20260323_0158"),
        ("orders", "0005_order_is_rated"),
        ("users", "0002_otpverification_name_otpverification_password_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(help_text="Rating from 1 to 5.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="users.customerprofile",
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="canteens.dish",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dish_ratings",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("dish", "customer", "order")},
            },
        ),
        migrations.DeleteModel(
            name="DishReview",
        ),
    ]
