# Generated by Django 5.2.12 on 2026-03-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canteens", "0005_dishrating_delete_dishreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canteen",
            name="aadhar_card",
        ),
        migrations.RemoveField(
            model_name="canteen",
            name="hall_approval_form",
        ),
    ]
