# Generated by Django 5.2.12 on 2026-03-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canteens", "0006_remove_aadhar_and_hall_form_columns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="discount",
        ),
    ]
