# Generated by Django 5.2.12 on 2026-04-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0007_remove_dish_discount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('canteen', 'name')},
        ),
    ]
