# POST http://127.0.0.1:8000/api/auth/register/
# Content-Type: application/json

# {
#     "email": "email@iitk.ac.in",
#     "password": "password"
# }

# {
#   "message": "Registration successful",
#   "user": {
#     "id": 8,
#     "email": "email@iitk.ac.in",
#     "role": "CUSTOMER",
#     "is_suspended": false,
#     "is_verified": true,
#     "created_at": "2026-03-18T23:23:05+0530"
#   }
# }

# ly0yl9vmy5noyj50nrmf1u4d8nth7083

# POST http://127.0.0.1:8000/api/users/wallet/add-funds/
# Cookie: sessionid=ly0yl9vmy5noyj50nrmf1u4d8nth7083
# Content-Type: application/json

# {
#     "amount": "100"
# }

POST http://127.0.0.1:8000/api/orders/place/
Cookie: sessionid=ly0yl9vmy5noyj50nrmf1u4d8nth7083
Content-Type: application/json

{
    "canteen_id": 2,
    "items": [
        {
            "dish_id": 9,
            "quantity": 3
        }
    ],
    "wallet_pin": "1234"
}

