# Generated by Django 6.0.3 on 2026-03-21 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_otpverification_name_otpverification_password_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('target_role', models.CharField(blank=True, default='', help_text='CUSTOMER, MANAGER, or empty string for ALL.', max_length=10)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.adminprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlaggedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('review', 'Review'), ('canteen', 'Canteen')], max_length=10)),
                ('content_id', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_items', to='users.adminprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('content_type', 'content_id')},
            },
        ),
    ]
