# Generated by Django 5.2.12 on 2026-03-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpverification",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="otpverification",
            name="password_hash",
            field=models.CharField(
                blank=True,
                help_text="Hashed password stored during initiate_signup",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="otpverification",
            name="role",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
