# Generated by Django 5.2.12 on 2026-03-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_pendingmanagerregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpverification",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="pendingmanagerregistration",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
