# Generated by Django 4.2.29 on 2026-04-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otpverification_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
