# Generated by Django 5.2.12 on 2026-04-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_roll_number_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='failed_attempts',
            field=models.IntegerField(default=0, help_text='Number of incorrect OTP attempts'),
        ),
    ]
