# Generated by Django 5.2.12 on 2026-03-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("canteens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price_at_order",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Effective price at time of order (after discount).",
                        max_digits=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("READY", "Ready for Pickup"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("REFUNDED", "Refunded"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("CONFIRMED", "Confirmed"),
                        ],
                        default="PENDING",
                        help_text="Current state — from Order Lifecycle state diagram.",
                        max_length=20,
                    ),
                ),
                ("book_time", models.DateTimeField(auto_now_add=True)),
                (
                    "receive_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when order is marked COMPLETED.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "canteen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="canteens.canteen",
                    ),
                ),
            ],
            options={
                "ordering": ["-book_time"],
            },
        ),
    ]
