# Generated by Django 5.2.12 on 2026-03-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_reject_reason_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason provided by manager when cancel request is denied.",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("READY", "Ready for Pickup"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                    ("REFUNDED", "Refunded"),
                    ("CANCEL_REQUESTED", "Cancel Requested"),
                    ("CANCELLED", "Cancelled"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("CONFIRMED", "Confirmed"),
                ],
                default="PENDING",
                help_text="Current state — from Order Lifecycle state diagram.",
                max_length=20,
            ),
        ),
    ]
