# Generated by Django 5.2.12 on 2026-03-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_is_rated"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the person picking up the order.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="roll_no",
            field=models.CharField(
                blank=True,
                help_text="Roll number for identification at pickup.",
                max_length=50,
            ),
        ),
    ]
