# Generated by Django 5.2.13 on 2026-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_customer_name_order_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pre_cancel_status',
            field=models.CharField(blank=True, help_text='Stores the status of the order before a cancellation was requested.', max_length=20, null=True),
        ),
    ]
