# Generated by Django 5.2.12 on 2026-03-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CakeReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flavor", models.CharField(max_length=100)),
                (
                    "size",
                    models.CharField(help_text="e.g., 0.5kg, 1kg, 2kg", max_length=50),
                ),
                ("design", models.CharField(blank=True, max_length=255)),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        help_text="Message to write on the cake (e.g., 'Happy Birthday').",
                        max_length=500,
                    ),
                ),
                ("pickup_date", models.DateField()),
                ("pickup_time", models.TimeField()),
                (
                    "advance_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIGURATION", "Configuration"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="CONFIGURATION",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason from manager if rejected (e.g., 'Capacity Full').",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
