# Generated by Django 5.2.12 on 2026-03-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cakes", "0001_initial"),
        ("canteens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cakereservation",
            name="canteen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cake_reservations",
                to="canteens.canteen",
            ),
        ),
    ]
