# Generated by Django 5.2.12 on 2026-04-08 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0003_initial"),
        ("canteens", "0007_remove_dish_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="CakeFlavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo of this cake flavor.",
                        null=True,
                        upload_to="cake_flavors/",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canteen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cake_flavors",
                        to="canteens.canteen",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("canteen", "name")},
            },
        ),
        migrations.CreateModel(
            name="CakeSizePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        help_text="e.g., 0.5 kg, 1 kg, 2 kg", max_length=50
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Advance amount for this size.",
                        max_digits=10,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canteen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cake_size_prices",
                        to="canteens.canteen",
                    ),
                ),
            ],
            options={
                "ordering": ["price"],
                "unique_together": {("canteen", "size")},
            },
        ),
    ]
