# Generated by Django 5.2.12 on 2026-04-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0004_cakeflavor_cakesizeprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cakeflavor",
            name="photo",
        ),
    ]
