# Generated by Django 4.2.29 on 2026-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_remove_cakeflavor_photo_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakereservation',
            name='status',
            field=models.CharField(choices=[('CONFIGURATION', 'Configuration'), ('PENDING_APPROVAL', 'Pending Approval'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='CONFIGURATION', max_length=20),
        ),
    ]
